# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:17.2.0  
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "checkout master"
          command: "git checkout master"
      - run:
          name: "checkout ."
          command: "git checkout ."
      - run:
          name: "pull"
          command: "git pull origin master"
      - run:
          name: "npm install"
          command: "npm install"
      - run:
          name: "run build"
          command: "npm run build"

workflows:
  build-workflow:
    jobs:
      - build
